name: Run Node.js Script Hourly

on:
  push:
    branches:
      - main
  schedule:
    # Runs at the start 5 minutes
    - cron: '*/5 * * * *'

jobs:
  execute-node-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          git config --global user.name 'Auto'
          git config --global user.email 'antogin@users.noreply.github.com'
      - name: Run script
        run: node charli.js
